### ISSUE TITLE
F250 and Tacoma missing from SO Lt.

### ISSUE THREAD

**Issue by AaronMichaels** [Hurstzy/ShorelineRoleplay#10]
**What is the bug, be thorough.**
Lieutenants within the SASO are supposed to have access to the F250 and the Tacoma (LEO101 and LEO100 on old menu) They currently do not. I believe Saucy gave Hurst an out of date vehicle list and never got around to sending in a fix 

**How can we reproduce this bug?**
Go to the LEO shop

**Images**
Heres the roster - https://i.gyazo.com/7cf7eac6e39b86419cdd1dbbb82ce99b.png and here is the vehicle shop I have access to as LT in SO

**Other info**
N/A

**Comment by Hurstzy** [comment]
Is it lieutenant+?

**Comment by AaronMichaels** [comment]
The Tacoma and the F250 are both supposed to be available for people Lieutenant and above.

I believe it is configured correctly for SASP, Saucy must've given you an out of date vehicle list.
https://docs.google.com/spreadsheets/d/1ouL3MZduKimXbRXcZy9Dqa-SSHaM1UKLNfiFO94njN0/edit#gid=122130669
Theres the roster with the vehicle guide, should be fairly easy for you to see what's needed for what. Hope this helps x

**Comment by Hurstzy** [comment]
This has been fixed for the next server restart.
