### ISSUE TITLE
Nerf Police Radars

### ISSUE THREAD

**Issue by MikeDouglass** [Hurstzy/ShorelineRoleplay#101]
**What is your suggestion?**
[Police radars are too powerful. The cop does not even have to see the back of the car and they can get the plate. Also they can clock people behind them from like a mile away. I feel they should have to be a lot closer for the plate. Also, tell me how it is possible for a back radar on a police car to read a plate on the back of a car. :/ The radars are WAYY too overpowered. *]

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by ComradGamingMC** [comment]
So there not that overpowerd, Now yes it can grab the plate from a good distance. But Police Radars IRL can get you from good distance. Also Most cars have front plates on the car so yea. But this is not something they can really fix, Sense the Plate Reader is not custom to Shoreline

**Comment by Hurstzy** [comment]
We can still nerf it regardless of if it is custom to us or not.

**Comment by AaronMichaels** [comment]
This is actually false; we're required to see the front or back to get the plate of the vehicle; hence why we have to angle the vehicles so harshly. Putting a car side on to a police radar doesn't give us the number plate x
