### ISSUE TITLE
Job Idea's for Civ update.

### ISSUE THREAD

**Issue by ComradGamingMC** [Hurstzy/ShorelineRoleplay#105]
**What is your suggestion?**
What is my suggestion, My suggestion is some jobs that involve trucking, So some basic ones would be a logging job. So there start at the logging area in Paleta Bay, and End it the city at the docs. Some other ones would say start at the say the City Docs, and end at the mine, or other places, Like LS Customes. or even stores, and Some other cool jobs would be transporting cars from the city docs, to say The Dealer Ship or even the airport to the dealership or from the dealership to the Airport or Dealership to the Docs. or even some fuel jobs, Where you start somewhere in the city or even in the county, and you fill a tanker with fuel and you drive around the different fuel stations (players choice) then you drop off the trailer at the docs, or even where you drive some say Air crafts that are attached to flatbeds and you pick them up at the docs and drop them off at the airports around the city, And same can be done with boats and even police boats. Just more trucking jobs that pay well. so players will want todo them more often 

Is your suggestion related to a current issue?
Yes & No, Yes because the issue of where we don't have many civ jobs, But not a major issue. (These are ideas for the first CIV update.

**Comment by Hurstzy** [comment]
Thanks for the suggestion.
