### ISSUE TITLE
Car despawning 

### ISSUE THREAD

**Issue by Viator38** [Hurstzy/ShorelineRoleplay#107]
**What is the bug, be thorough.**
[answer here *i was mining then took a flight out i had my mustang with me up their, when i head back in i go to the garage and see if he was there its gone. ]

**How can we reproduce this bug?**
[answer here *Have car automatically save in garage when taking a flight out *]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *Will i be able to get my car back?*]

**Comment by Hurstzy** [comment]
Your car will return after a server restart.
