### ISSUE TITLE
Air one not spawning

### ISSUE THREAD

**Issue by PF1anagan** [Hurstzy/ShorelineRoleplay#109]
**What is the bug, be thorough.**
Air one helicopter does not spawn on Mission Row roof for the majority of people

**How can we reproduce this bug?**
Attempt to spawn Air One at MRPD

**Comment by Hurstzy** [comment]
Do you get an error code or anything?

**Comment by PF1anagan** [comment]
No error codes, you select it and nothing happens. Blayze was able to spawn it at a civilian garage in Legion Square but it crashed anyone that tried to get into it.

**Comment by Hurstzy** [comment]
We are working on this.
