### ISSUE TITLE
!! Police Dogs !!

### ISSUE THREAD

**Issue by AaronMichaels** [Hurstzy/ShorelineRoleplay#123]
**What is your suggestion?**
We got Pets for Civs and we can buy them as cops, but can we get added functionality to them? 

Even if just as a cop we can buy the K9 Ped that gets the vest, and an attack "order". Please? Support Division in SO is down but not out yet, Helicopters still don't work and boats are rarely used as-is but reviving K9 would be amazing. -

Is your suggestion related to a current issue?
Civ pets - it's an extension, I suppose.

**Other info**
This would really be something amazing for SO, our K9s were amazing. Thank you in advance.

**Comment by Jamesmayl** [comment]
and SASP :)

**Comment by Hurstzy** [comment]
This is in the works.
