### ISSUE TITLE
[LEO] Null Vehicle types in garage

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#131]
**What is the bug, be thorough.**
May be related to my last bug report about some LEO vehicles not purchasing -- the last 3 vehicles I purchased have vehicle types of NULL

**How can we reproduce this bug?**

**Images**
![image](https://user-images.githubusercontent.com/67668058/96628080-c65e2e00-12df-11eb-93e8-7930510156d8.png)

**Other info**

**Comment by SammyB8185** [comment]
What are the three vehicles @factorAD

**Comment by factorAD** [comment]
no clue @SammyB8185 . Database wipe should help if/when it happens. I'll keep better track once I have a clean garage
