### ISSUE TITLE
Can not eat.

### ISSUE THREAD

**Issue by fools33** [Hurstzy/ShorelineRoleplay#136]
**What is the bug, be thorough.**
I died earlier and when I respawned my burgers were never removed from my inventory, now any time I try to eat it says action impossible. I have dropped the burgers, tried to purchase new and still get the same problem. I also noticed I had a script error.

**How can we reproduce this bug?**
I am unsure of how to reproduce this issue.

**Images**
![Burger Script Error](https://user-images.githubusercontent.com/73200932/96648383-43e46700-12fd-11eb-94b2-a5e26aa4867d.png)

**Other info**
The character I am having this issue on is Vincent Antolini

**Comment by factorAD** [comment]
Closing this due to age - open a new ticket if it persists please
