### ISSUE TITLE
New CAD?? 

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#139]
https://forum.cfx.re/t/preview-wip-esx-cad-system/722134 

Any update on a new cad

**Comment by factorAD** [comment]
The ability to see what’s going on around you while in the CAD is important

**Comment by ThePublicServant** [comment]
Atleast I'm contributing ideas

**Comment by factorAD** [comment]
Not giving you crap, just contributing ideas as well.

**Comment by Hurstzy** [comment]
Our CAD will come sooner than later. 
Also that link is a WIP (work in progress) meanings its not out yet.
