### ISSUE TITLE
TEU/TED Bike not in game

### ISSUE THREAD

**Issue by Jamesmayl** [Hurstzy/ShorelineRoleplay#14]
**What is your suggestion?**
[add back the TEU/TED bike code: [1200RT]

Is your suggestion related to a current issue?
[no]

**Other info**
[---------]

**Comment by Hurstzy** [comment]
Are you SASP or BCSO?

**Comment by Jamesmayl** [comment]
I am SASP, its for Traffic Enforcement, it was in the old city.

**Comment by Hurstzy** [comment]
Will be fixed next restart.
