### ISSUE TITLE
AI Balancing/Script

### ISSUE THREAD

**Issue by NotAaronScott** [Hurstzy/ShorelineRoleplay#152]
**What is your suggestion?**
Add a AI script to balance the AI. Ex. You may not see any for 15 minutes and sometimes they desync and fall through the map. Its a huge immersion breaker and just ruins my mood to RP. By fixing this it would make the city feel more alive and keep the players blended into the general traffic much better rather than seeing 1 car and knowing it is a player.

Is your suggestion related to a current issue?
Of course, the amount of AI issues are insane.

**Other info**
This may seem very unimportant, but when AI isn't functional it makes the world seem non existent.

**Comment by factorAD** [comment]
Potential fix 1/16/21
