### ISSUE TITLE
LEO Car Shop won't open?

### ISSUE THREAD

**Issue by AaronMichaels** [Hurstzy/ShorelineRoleplay#155]
**What is the bug, be thorough.**
As of today; I am unable to open the LEO shop at all. I do not get any form of sound confirmation that I have done the action.. I simply cannot open the menu?

**How can we reproduce this bug?**
Try to buy an LEO car?

**Images**
n/a

**Other info**
It seems to be only affecting me out of all the LEOs I have asked :|

**Comment by factorAD** [comment]
Fixed
