### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by javin12** [Hurstzy/ShorelineRoleplay#158]
**What is the bug, be thorough.**
Whenever an leo sits in his vehicle, it sometimes crashes the game of other people around the officer and then they have to relog.

**How can we reproduce this bug?**
Sit in an leo car with someone else around

**Images**
N/A

**Other info**
[any other info? *remove this line to answer*]

**Comment by factorAD** [comment]
Potential fix released 1/17/21 and the server is currently being optimized in addition
