### ISSUE TITLE
Harley Davidson Turning Radius

### ISSUE THREAD

**Issue by RayzRayz** [Hurstzy/ShorelineRoleplay#16]
**Why do you purpose this balance?**
[The Harley Davidson purchasable in the Premium Deluxe Motorsports Dealership has an awful turn radius for a motorcycle. It doesn't even make left or right hand turns within a two-three lane roads. ]

**What is your solution?**
[Just tweak the turning radius for the motorcycle to make it more driveable and realistic please.]

**Other info**
[The model is beautiful. Other than the handling and turning that is all. Thank you.]

**Comment by SammyB8185** [comment]
This should be fixed in the next restart. Let me know if it is not.
