### ISSUE TITLE
**AMR** Vehicles costing money and we have to pay for gas.

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#162]
**What is the bug, be thorough.**
AMR vehicles and gas costing money.

**How can we reproduce this bug?**
Get on as AMR

**Other info**
The reason why this is a "bug" is because our members have to buy gas, vehicles, AND a 900 dollar phone to go on duty.

**Comment by Hurstzy** [comment]
AMR is a privately owned ambulance company therefore they have to pay for there equipment ect.

LEO vehicles will end up costing money again though.
