### ISSUE TITLE
Courts suggestion 

### ISSUE THREAD

**Issue by Astro868** [Hurstzy/ShorelineRoleplay#166]
**What is your suggestion?**
[When you receive a citation you must go to the court house to pay it (etc. you receive a speeding ticket you cannot pay this by just hitting f7 you must go to a blip at the court house to pay it off]

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by factorAD** [comment]
Added
