### ISSUE TITLE
You need two phones to open the F1 menu

### ISSUE THREAD

**Issue by Intair** [Hurstzy/ShorelineRoleplay#168]
**What is the bug, be thorough.**
To use the F1 menu it is requiring me to have two phones in my inventory 

**How can we reproduce this bug?**
Buy one phone, Try and open F1 menu

**Images**
[With two phones](https://cdn.discordapp.com/attachments/764631094476800010/772535584920043520/unknown.png)
[With one phone](https://cdn.discordapp.com/attachments/764631094476800010/772535688549498951/unknown.png)

**Other info**
nope

**Comment by factorAD** [comment]
Appears to be working. If you experience again open a new ticket with steps to reproduce
