### ISSUE TITLE
Unable to buy LEO cars.

### ISSUE THREAD

**Issue by AaronMichaels** [Hurstzy/ShorelineRoleplay#182]
**What is the bug, be thorough.**
Simply aren't able to buy cars, many members of LEO and most notable is many members of LEO HC can't buy cars?

**How can we reproduce this bug?**
Try to buy a police car? idk

**Images**
My error: https://cdn.discordapp.com/attachments/645666291507789826/774311390676123648/unknown.png
Charlie LaRoux gets the same error: https://cdn.discordapp.com/attachments/645666291507789826/774311390676123648/unknown.png

**Other info**
the error is the same for all of us I believe

**Comment by factorAD** [comment]
Fixed
