### ISSUE TITLE
[LEO] Breathalyzer always passes test sober

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#185]
**What is the bug, be thorough.**
I believe the breathalyzer always returns "Passes Test. Sober" - we had an individual who was drinking and swaying around yesterday who passed two separate breathalyzer tests.

**How can we reproduce this bug?**
Drink / have a breathalyzer administered

**Images**

**Other info**

**Comment by Hurstzy** [comment]
The breathalyzer is broke right now.

**Comment by Hurstzy** [comment]
You have to give the breathalyzer to the civ and they use it, yet the script won't return the outcome to the cop, only the civ.

**Comment by Hurstzy** [comment]
Well scratch that lol, the cop sees the result but the civ has to use the breathalyzer.
