### ISSUE TITLE
Ability to remove LEO vehicles in Garage

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#19]
**What is your suggestion?**
my LEO garage if full of cars due to all the issues from the past and the random despawning... would love to be able to remove the 45 cars i dont need

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by Hurstzy** [comment]
I can remove these manually, but that is why I never wanted to make LEO cars free because when people destroy them they just get a new one for free which just leads to this to have 50 cars that aren't available in ur garage.
