### ISSUE TITLE
[LEO Suggestion] Some form of K9 RP

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#190]
**What is your suggestion?**
Add a script to make K9 RP possible. W/o pseudo-chat-rp such as `gme runs dog around car - does he alert?` there is no genuine opportunity for K9 RP.

Is your suggestion related to a current issue?
n/a

**Other info**
https://forum.cfx.re/t/release-ar-k9-1-2-standalone/1061030
Would need some TLC, but seems like a good foundation

**Comment by Jamesmayl** [comment]
yessss
