### ISSUE TITLE
[LEO Suggestion] Improved LEO Weapons

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#191]
**What is your suggestion?**
After the purge and the rise of various gangs within the city, LEO's frequently find themselves outpowered by black market guns.
An improved AR is requested to keep LEO alive.

Is your suggestion related to a current issue?
no

**Other info**
We keep getting gunned down; at an unrealistic rate.

**Comment by MisterSandman401** [comment]
It's possible to adjust firearm handling for the Combat Rifle in-game and add a new weapon model with working sights and attachments. We will look into it.

**Comment by factorAD** [comment]
New AR implemented
