### ISSUE TITLE
DNA Tracker (Bullet casing and blood )

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#192]
**What is your suggestion?**
DNA Tracker (Bullet casing and blood)
https://i.imgur.com/kpAgdnX.jpg
https://i.imgur.com/LnEGpG3.jpg

Is your suggestion related to a current issue?
Somewhat yes, the only Investigating RP we can do is the criminal either leaving us a note, talking with us, or bank cameras.

**Other info**
This is a paid script, but I have access to it if it were to be added to the server.

**Comment by MisterSandman401** [comment]
We have a version of this in the works right now. However, we can push this idea further and take a look into this.

**Comment by factorAD** [comment]
Added
 - Change log 12/05/2020
