### ISSUE TITLE
Disable police academy building

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#193]
**What is your suggestion?**
Disable, at least temporarily, the police academy building. It causes a lot of lag at MRPD and isn't being used by either department

Is your suggestion related to a current issue?
-

**Other info**
-

**Comment by PF1anagan** [comment]
^^

**Comment by factorAD** [comment]
It's come to my attention that it is sometimes used. Maybe an alternative that doesn't cause so much lag

**Comment by MisterSandman401** [comment]
I believe this was just removed. Confirm? I noticed it was laggy too.

**Comment by factorAD** [comment]
Implemented
