### ISSUE TITLE
Gun Models and Attachment Fix

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#197]
**What is your suggestion?**
Add these following weapon models. The current ones are oudated and attachments don't work, like the ACOG sight for the rifle for example. The current Glock model on the combat pistol has horrible reticles and is low quality. 

Pistol - https://www.gta5-mods.com/weapons/beretta-m9-animated
Shotgun - https://www.gta5-mods.com/weapons/mossberg-590-animated
Police AR - https://www.gta5-mods.com/weapons/m4a1-eotech-acog-carry-handle-animated
Police Pistol - https://www.gta5-mods.com/weapons/glock-20-va5
SNS Pistol - https://www.gta5-mods.com/weapons/hk-compact-45-animated
Civilian Assault Rifle - https://www.gta5-mods.com/weapons/ak-47-animated

Is your suggestion related to a current issue?
No. But I believe this would greatly increase immersion and roleplay with handling real firearms. You could rename the items in the store to the real life gun model names. Also, an attachment fix would be great for police armoury. 

**Other info**
[any other info? *delete this line to answer*]

**Comment by Hurstzy** [comment]
I added the models you linked if the gun is available in game, more models would be appreciated as you find them.
