### ISSUE TITLE
Shirt

### ISSUE THREAD

**Issue by AdvanceGamerPlayz** [Hurstzy/ShorelineRoleplay#202]
**What is the bug, be thorough.**
[/shirt no longer works]

**How can we reproduce this bug?**
[try /shirt]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
This is not a bug, the changelog on 11/16 addressed this.
