### ISSUE TITLE
Taxi Company On-Off duty issue

### ISSUE THREAD

**Issue by RayzRayz** [Hurstzy/ShorelineRoleplay#204]
**What is the bug, be thorough.**
Employees are not able to go on / off duty at the yellow circle. It will notify you that you have "gone off duty" but remain to pay you the income every so often which drains the company funds when they are not actively taxiing. 

**How can we reproduce this bug?**
Employ yourself with the taxi job and try to go on and off duty. You also still have access to the F6 menu. 

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
Other than that I believe the vehicles still spawn sideways in the garage making it hard to get out safely.

**Comment by Hurstzy** [comment]
This will be resolved tomorrow.
