### ISSUE TITLE
Jerry can bug/Problem

### ISSUE THREAD

**Issue by ComradGamingMC** [Hurstzy/ShorelineRoleplay#205]
**What is the bug, be thorough.**
What is the bug, The bug i am reporting is about the jerry can, So the bug would when you purchase a jerry can from a gas pump, And it gets put away, You are not able to pull out the jerry can again, Then it stop you from purchasing another one. Then also when u have one that has some fuel in it, and it gets put away and you refill it. You still cant put it away

**How can we reproduce this bug?**
How can you reproduce this bug? You can reproduce this bug by going to a gas station and purchase a jerry can, Then you can also reproduce the second part by emptying the fuel can about putting it away and repurchase it.

**Other info**
My suggestion to fix this would be to find a ESX gas can, or a gas can model and put it in-game so it works with are inv system we have so we could put it in are hot bar and click on it and it would go into are hands.

**Comment by Hurstzy** [comment]
This has been resolved for tonight's update.
