### ISSUE TITLE
Fuel system change/fix

### ISSUE THREAD

**Issue by ComradGamingMC** [Hurstzy/ShorelineRoleplay#206]
**What is your suggestion?**
What is my suggestion, My suggestion would be to add in a different fuel system or remove the function of when your low on fuel, it would stop the truck from going back and forth as this cause many problems where once you hit 8 fuel it starts to spit & sputter and start applying the brakes and will try to reverse, 

Is your suggestion related to a current issue?
Is my suggestion related to a current issuse, I think it is, but at the same time it is not really a current issue

**Other info**
I would maybe look at other ESX Fuel script to see if we could or even talk with a dev, and see if they can rework that part of the script

**Comment by Hurstzy** [comment]
Fuel consumption was adjusted as of 12/1.
