### ISSUE TITLE
Give Players more Starting Cash

### ISSUE THREAD

**Issue by OPENCADSMSO** [Hurstzy/ShorelineRoleplay#209]
**What is your suggestion?**
Give players in the server more starting cash to atlease get a crappy vehicle to transport themself, get a weapon if needed or just blow it all.

Is your suggestion related to a current issue?
Yes it is. 

**Other info**
I think people should have a decent amount of cash to start of with to JUMPSTART their time here in shoreline instead of having to find transportation to get a job that usally involved a stolen vehicle, then you get arrested. More Cash would be AWESOME!

**Comment by ComradGamingMC** [comment]
I could kinda agree with these, Put a cheap car in PDM for people to buy nothing fancy, And enough cash to buy it, and buy a phone and food
