### ISSUE TITLE
[LEO] Vehicles become unlockable 

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#218]
**What is the bug, be thorough.**
After a client crash, or some other event that interrupts the connection, LEO vehicles sometimes become unlockable.
Unlocking the vehicle returns "Vehicle Unlocked" - but you cannot get into the vehicle.

**How can we reproduce this bug?**
Have a LEO car out of the garage. 
Crash your client (do this by having a separate person with the policejob get into their vehicle)
Reload FiveM
Attempt to unlock your vehicle

**Images**
https://streamable.com/tg4e2k

**Other info**
The car that is now undrivable, will also not return to your LEO garage.

**Comment by Hurstzy** [comment]
Fixed for tonight
