### ISSUE TITLE
LEO Vehicle Configs 

### ISSUE THREAD

**Issue by StokesyBoi** [Hurstzy/ShorelineRoleplay#228]
**What is the bug, be thorough.**
When customising an LEO vehicle in the LEO garage, once put back into the garage, the customisation you've done to it doesn't save when you get it back out.

**How can we reproduce this bug?**
Customise an LEO vehicle, put it in the garage then bring it out again, customisation isn't saved.

**Images**
None

**Other info**
None

**Comment by Hurstzy** [comment]
This is not a bug this just does not exist as you can customize your car freely when retrieving it.
