### ISSUE TITLE
Vehicle "Locked" and "Unlocked" notifications are reversed

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#231]
**What is the bug, be thorough.**
When you lock your car, you are notified that your vehicle was unlocked and vice versa.

**How can we reproduce this bug?**
Lock/unlock vehicle

**Images**
https://streamable.com/y5eh0b

**Other info**

**Comment by Hurstzy** [comment]
Fixed for next restart.
