### ISSUE TITLE
Pouring Gas Is WAY To Stressful

### ISSUE THREAD

**Issue by VyseM4H** [Hurstzy/ShorelineRoleplay#233]
**Why do you purpose this balance?**
[a thorough description for your balance request *remove line to answer*]
Because for 1 second of pouring gas on the ground your stress skyrockets and unless you got a fist full of ciggies your dead.
**What is your solution?**
[a thorough description for your balance solution *remove line to answer*]
Make it considerably less stressful? I understand the fumes of the gas can get to you but god damn!
**Other info**
[any other info? *remove line to answer*]

**Comment by Hurstzy** [comment]
This is not intentional and will be fixed.
