### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by StokesyBoi** [Hurstzy/ShorelineRoleplay#235]
**What is the bug, be thorough.**
Controller support works for about 5 minutes then it cuts out.

**How can we reproduce this bug?**
Be on the server, after a couple minutes controller support just stops working.

**Images**
None
**Other info**
I'm not sure if something triggers it but it's not just me, EMS was having the same problem at the time.

**Comment by Hurstzy** [comment]
I think this is just you, a majority of players using controller have nothing but good to say about it, contact fools33 and maybe he can help you as he mainly uses controller.
