### ISSUE TITLE
Game crashes as soon as you enter Blaine county.

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#237]
**What is the bug, be thorough.**
Game crashes as soon as you enter Blaine county.

**How can we reproduce this bug?**
Drive into Blaine county, near 4000.

**Images**
[CfxCrashDump_2020_12_07_21_34_38.zip](https://github.com/Hurstzy/ShorelineRoleplay/files/5655380/CfxCrashDump_2020_12_07_21_34_38.zip)

**Other info**
If needed I can create a video of recreating this bug.

**Comment by SlumpyShoreline** [comment]
Cap

**Comment by factorAD** [comment]
If this issue persists after 1/16/21, open a new ticket with steps to recreate the bug please
