### ISSUE TITLE
[LEO] Sandy/Poledo PD have no cloakroom/vest blips

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#239]
**What is the bug, be thorough.**
Sandy PD (and reportedly, Poledo) are missing the cloakroom and vest blips. Only the armory and society management blips appear

**How can we reproduce this bug?**
No special steps - this was confirmed by a Senior Trooper as well, so it's not rank related

**Images**
-
**Other info**
-

**Comment by Hurstzy** [comment]
This is fixed for the next restart.
