### ISSUE TITLE
Honda Civic Type R Handling 

### ISSUE THREAD

**Issue by AdvanceGamerPlayz** [Hurstzy/ShorelineRoleplay#24]
**What is the bug, be thorough.**
[The Honda Civic Type R has bad handling flips pretty easy]

**How can we reproduce this bug?**
[Take a turn somewhat fast]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
Sammy, note this vehicle it VERY fast for its type, please nerf the speed a bit as well.

**Comment by SammyB8185** [comment]
This should be fixed with the next restart. If not please let me know.
