### ISSUE TITLE
[LEO] No blip to test Blood Sample

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#240]
**What is the bug, be thorough.**
You can collect blood samples, but there is no blip in the MRPD briefing room to test them. Also, the computer near the cells isn't functional.

**How can we reproduce this bug?**
No steps necessary to reproduce the missing blip. 

**Images**

**Other info**

**Comment by Hurstzy** [comment]
There is a blip in MRPD, it is in the left corner.

**Comment by factorAD** [comment]
Turns out it is just broken in the main server. @Hurstzy
