### ISSUE TITLE
Harley Davidson handling

### ISSUE THREAD

**Issue by jacobm9** [Hurstzy/ShorelineRoleplay#25]
**What is the bug, be thorough.**
The Harleys handling line is like a Big Mac truck 

**How can we reproduce this bug?**
Update or find a hand line line to fit the bike

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
This should be fixed for the next restart. If not please let me know.
