### ISSUE TITLE
Supra

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#252]
**What is the bug, be thorough.**
My $214,000 1998 Toyota Supra doesn't take paint, even though i see others with painted cars and the add-on's (skirts, bumpers,
hoods) make the other parts turn purple sometimes.

**How can we reproduce this bug?**
i have no idea, just looking for some clarity.

**Comment by Hurstzy** [comment]
All issues regarding the supra have been resolved and will be live next server restart.
