### ISSUE TITLE
food and drink bug

### ISSUE THREAD

**Issue by Myang876** [Hurstzy/ShorelineRoleplay#254]
**What is the bug, be thorough.**
say you have 3 stacks of 6 burgers and you eat 1 burger from one of the stack then leave it will set all the other stack down to 5  

**How can we reproduce this bug?**
eat a burger from a stack then leave and rejoin 
**Images**
https://user-images.githubusercontent.com/75805468/101812637-3cf9f980-3ae1-11eb-8751-482f84cac3d5.png [Before relog]
https://user-images.githubusercontent.com/75805468/101812826-80ecfe80-3ae1-11eb-8035-42607cbf0987.png [after relog]

**Other info**
[any other info? *remove this line to answer*]

**Comment by DerekStealth** [comment]
do /ensureInv with the capital i

**Comment by Hurstzy** [comment]
This will be resolved with an upcoming inventory update.
