### ISSUE TITLE
C7 zr1

### ISSUE THREAD

**Issue by trkrdan** [Hurstzy/ShorelineRoleplay#256]
**What is the bug, be thorough.**
Textures are broken on the car, some parts on the car change color or disappear all together while walking around the car or moving your camera. The wheels also look plastic. It also only has white lights on the rear.

**How can we reproduce this bug?**
Spawn the car and walk around it or move your camera around.

**Images**
![zr1_4](https://user-images.githubusercontent.com/75818808/101850663-70f01180-3b17-11eb-8fce-20817c95e45a.PNG)
![Uploading zr1_3.PNG…]()
![zr1_2](https://user-images.githubusercontent.com/75818808/101850674-7a797980-3b17-11eb-8acc-f3da847369e2.PNG)

**Comment by Hurstzy** [comment]
Fixed for next restart.
