### ISSUE TITLE
[LEO] Body Armor

### ISSUE THREAD

**Issue by xcode55** [Hurstzy/ShorelineRoleplay#257]
**What is your suggestion?**
Enable the feature of grabbing your body armor as a part of your outfit instead of having to grab it as a prop and move the actual purchase of body armor to the armory. 

Is your suggestion related to a current issue?
Every time an LEO does /hat or /clothes or crashes, said LEO every time has to go back to station mainly MRPD since none of the other stations on the map has a working purchase feature of the current way getting body armor works. 

**Other info**
[any other info? *delete this line to answer*]

**Comment by factorAD** [comment]
Sandy Shore PD blips for vest / armory / uniform are all fixed
