### ISSUE TITLE
Holiday Lights floating in air.

### ISSUE THREAD

**Issue by SheriffBoy** [Hurstzy/ShorelineRoleplay#259]
**What is your suggestion?**
Add strings to the Christmas lights floating on the road to look more legit.

Is your suggestion related to a current issue?
The Christmas Lights are floating and it gives it an unrealistic feel to it. Adding strings to them, would make it look much more legit.

**Comment by Hurstzy** [comment]
We did not create the map so it is unfortunately not possible.
