### ISSUE TITLE
[LEO] 911 calls

### ISSUE THREAD

**Issue by xcode55** [Hurstzy/ShorelineRoleplay#262]
**What is your suggestion?**
This is a **two-part suggestion**

1.  First part is marking 911 calls on the map so it's visible to LEOs and after 30 seconds or so, it will disappear from the map. This will also include panic buttons. 

2.  Second part is supporting the first. Make a chat command like "/mark911" which will set a waypoint to the last 911 within 5-15 seconds.

Is your suggestion related to a current issue?
Nope

**Other info**
N/A

**Comment by factorAD** [comment]
Part 1 has been implemented
Part 2 was addressed in Changelog 1/18/21 - you can set your GPS to the location of the call from within the MDT
