### ISSUE TITLE
SASO Can't See SAST And DPS Blimps

### ISSUE THREAD

**Issue by Jamesmayl** [Hurstzy/ShorelineRoleplay#266]
**What is the bug, be thorough.**
[On The GPS/minimap SASO deputies cannot see the SAST/DPS blimps which makes it really hard to to find someone in a pursuit or in general to find someone]

**How can we reproduce this bug?**
[Get a SASO Job and go on duty and you will not see any SAST/DPS blimps]

**Comment by DerekStealth** [comment]
**facts they need to fix this**

**Comment by Jamesmayl** [comment]
yup

**Comment by factorAD** [comment]
Fixed with a caveat...blips only show within "300 units" of a player - this is due to OneSync Infinity which was recently implemented and is important for server optimization
