### ISSUE TITLE
AIs need to be looked into

### ISSUE THREAD

**Issue by xProlithium** [Hurstzy/ShorelineRoleplay#273]
**What is the bug, be thorough.**
The AI vehicles acting the way they do. Whatever AI script is being used (if there is one) really need to be changed.

**How can we reproduce this bug?**
Drive down the highway. Cars falling from the sky, cars in the middle of the road. Entire highways blocked off with cars.

**Images**
https://i.imgur.com/eBl5PfC.jpeg
https://i.imgur.com/WIzT7ow.jpg

**Other info**
This isn't a FiveM issue, I only see this happen on this server.

**Comment by factorAD** [comment]
This will be fixed soon, thanks

**Comment by factorAD** [comment]
Potential fix released 1/16/21
