### ISSUE TITLE
Used Car Lot

### ISSUE THREAD

**Issue by StokesyBoi** [Hurstzy/ShorelineRoleplay#277]
**What is your suggestion?**
Clear the used car lot.

Is your suggestion related to a current issue?
Yes, people have filled up the used car with vehicles you find on the street and overpriced vehicles, and people actually wanting to sell vehicles can't because of the amount of random vehicles filling up spaces.

**Other info**
No

**Comment by Hurstzy** [comment]
This system is being reworked for the large scale update this month.
