### ISSUE TITLE
Gasoline trucking mission broken

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#278]
**What is the bug, be thorough.**
when you go to pick up the trailer it doesnt show up

**How can we reproduce this bug?**
just go do the mission

![20201229110804_1](https://user-images.githubusercontent.com/72358295/103308197-b1300a80-49c6-11eb-9eed-a770337c635c.jpg)

**Comment by factorAD** [comment]
Is this issue still active or is it outdated since the trucking job has been reworked (1/02/2021)?
