### ISSUE TITLE
AMR Stretcher Bug

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#28]
**What is the bug, be thorough.**
AMR Stretcher Popcorns for everyone except for the person that spawns it

**How can we reproduce this bug?**
spawn in the stretcher

**Comment by ShorelineLeo** [comment]
Updates?

**Comment by Hurstzy** [comment]
Popcorns? Can you reword this issue with more detail and screenshots?
