### ISSUE TITLE
Audi R9 V10 Plus

### ISSUE THREAD

**Issue by davey24** [Hurstzy/ShorelineRoleplay#282]
**What is your suggestion?**
The Audi R8 V10 Plus in game is quite unrealistic. The car in real life goes 198 top speed, but the car model in the game with full performance upgrades only goes 125.
Is your suggestion related to a current issue?
Yes, like stated the speed is not realistic.

**Other info**

**Comment by NotAaronScott** [comment]
The speed is based on a wide variety of factors but most importantly, vehicle balance within the community.
