### ISSUE TITLE
Bank Robbery Alert

### ISSUE THREAD

**Issue by PF1anagan** [Hurstzy/ShorelineRoleplay#283]
**What is the bug, be thorough.**
When a bank alarm is triggered, it appears to Law Enforcement as ALL banks being robbed. See image.

**How can we reproduce this bug?**
Have someone rob a bank and be clocked on as a LEO.

**Images**
https://cdn.discordapp.com/attachments/729053721463488614/796083959435231232/unknown.png

**Comment by factorAD** [comment]
This is either going to fix itself with OneSync infinity,
or break in such a way that the entire notification script will get re-looked at and re-coded.

In any event, this should be fixed soon

**Comment by factorAD** [comment]
Potentially fixed with OneSync. Please open a new issue if it reoccurs
