### ISSUE TITLE
hunting

### ISSUE THREAD

**Issue by trkrdan** [Hurstzy/ShorelineRoleplay#285]
**What is your suggestion?**
make it so where we can eat the animal meet vs selling it. as we as fishing from streams and gather water from streams or small bodies of water. basically a system where we can live out in the mountains off the grid 

Is your suggestion related to a current issue?

**Comment by Hurstzy** [comment]
Thank you for your suggestion/bug report! This has been taken into consideration and will be included in the large scale update releasing this month.
