### ISSUE TITLE
Sheriff's Office 2020 Explorer

### ISSUE THREAD

**Issue by StokesyBoi** [Hurstzy/ShorelineRoleplay#287]
**What is the bug, be thorough.**
The front grill lights and mirror lights on the 2020 explorer don't work.

**How can we reproduce this bug?**
Try using the explorer's lights with the last extra enabled and disabled, on or off they don't work.

**Images**
[https://cdn.discordapp.com/attachments/782257540104454194/797121898462314546/unknown.png](url)

**Other info**
I think possibly the missing lights have ended up underneath the vehicle at the rear.

**Comment by AaronMichaels** [comment]
The 2020 explorer we have in SO has been broken for a long time, and with the SO vehicle update around the corner I can't imagine we'll be seeing this be fixed as it would be a waste of dev time.

**Comment by factorAD** [comment]
> The 2020 explorer we have in SO has been broken for a long time, and with the SO vehicle update around the corner I can't imagine we'll be seeing this be fixed as it would be a waste of dev time.

This.

We can reassess vehicles after the new pack is in
