### ISSUE TITLE
Dysfuncional Spike Strips

### ISSUE THREAD

**Issue by PF1anagan** [Hurstzy/ShorelineRoleplay#290]
**What is the bug, be thorough.**
Law Enforcement's Spike Strips don't seem to be working.

**How can we reproduce this bug?**
Attempt to spike a car.

**Proof**
https://youtu.be/8bdKP7wikTo
https://youtu.be/F_-3CalnSoc

**Comment by factorAD** [comment]
They seem to be functional under ~60mph, however, we're gonna take a look at adjusting that higher

**Comment by factorAD** [comment]
After extensive testing, this seems to be a limitation of FiveM. A slightly altered version is live, and will hopefully make successful spikes more consistent. We're unable to do more beyond what we've done.
