### ISSUE TITLE
Heli Repair Kit doesn't work

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#291]
**What is the bug, be thorough.**
When trying to repair a helicopter with a repair kit, it says item used, doesn't take it out of your inventory, and doesn't work 

**How can we reproduce this bug?**
try to repair a broken heli with a repair kit

**Comment by factorAD** [comment]
Hey Leo

If you get some free time, could you possibly record a short clip of you attempting to use a repair kit on a helicopter?
Seeing the exact sequence of events would help narrow down exactly what is breaking and where. Also if you could check f8 console for any errors

**Comment by Hurstzy** [comment]
Thank you for your suggestion/bug report! This has been taken into consideration and boat/aviation mechanic shops will be included in the large scale update releasing this month.
