### ISSUE TITLE
meat sales

### ISSUE THREAD

**Issue by IMrRebelJnr** [Hurstzy/ShorelineRoleplay#292]
**What is the bug, be thorough.**
some meat like cougar and deer meat do not sell. "you have no meat to sell" 

**How can we reproduce this bug?**
scripting?

**Images**
[answer here if you have images *remove this line to answer*]
**Other info**
[any other info? *remove this line to answer*]

**Comment by factorAD** [comment]
Doesn't appear to be reproducible...selling deer and cougar meat works fine for us.

Try /ensureInv and if it still doesn't work, create a new issue with steps to reproduce the bug

**Comment by factorAD** [comment]
As of 1/18/21 we were able to reproduce the bug and release a potential fix.
If you experience this issue after 1/18/2021 20:30:00 PST (scheduled server restart) please create a new ticket.
