### ISSUE TITLE
new mdt

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#293]
https://forum.cfx.re/t/esx-hypaste-rps-mobile-data-terminal-reports-warrants-calls-searches-more/1701472

**Comment by factorAD** [comment]
This is the same script we have in for the most part. Are there specific features you're requesting?

**Comment by ThePublicServant** [comment]
in the video it showed the mdt would auto run plates for you and it had a call function so we can prioritize calls comming in i thought it would help us and looked updated then what we had

**Comment by factorAD** [comment]
Yeah we've played around with the MDT before, it's a relatively messy script as is so I'm personally hesitant to attempt the call board as I think it would break more often than not.

The auto plate thing is cool though. I'll look into that.
We can look at refreshing the UI as well

**Comment by Hurstzy** [comment]
Ill look into it

**Comment by factorAD** [comment]
Change log 1/18/21
