### ISSUE TITLE
Vehicle breakdown script

### ISSUE THREAD

**Issue by RCBlitz** [Hurstzy/ShorelineRoleplay#296]
**What is your suggestion?**
There was before but when your car is basically fucked up to the point undriveable to make it more realistic make it so the vehicle will break and engine won’t turn on

Is your suggestion related to a current issue?

**Other info**
With this script in it could add for more rp and better rp with vehicle crashes instead of people just continueing because no body is around. This will also help better out pursuits so when the suspect crashes they can’t just continue

**Comment by Hurstzy** [comment]
Thank you for your suggestion/bug report! This has been taken into consideration and a similar system will be included in the large scale update releasing this month.
