### ISSUE TITLE
Unable to sell meat

### ISSUE THREAD

**Issue by xProlithium** [Hurstzy/ShorelineRoleplay#297]
**What is the bug, be thorough.**
Still cannot sell meat at the meat buyer.

**How can we reproduce this bug?**
Try selling to the meat buying at night.

**Images**
https://i.imgur.com/KH7h9hc.jpeg

**Other info**
If it matters, I stored the meat in the glove box of my vehicle first.

**Comment by Hurstzy** [comment]
Thank you for your suggestion/bug report! This has been taken into consideration and will be included in the large scale update releasing this month.
