### ISSUE TITLE
Random blip

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#3]
**What is the bug, be thorough.**
There is a random white blip in the middle of the road at 8168

**How can we reproduce this bug?**
Drive to the area and check if it's there. There was no action taken by me immediately prior to this occuring.

**Images**
https://i.imgur.com/FTLa208.png

**Other info**
n/a

**Comment by Hurstzy** [comment]
That is not a bug, someone dropped an inventory item there, standing on the marker and hitting f2 will show you what was dropped there.
