### ISSUE TITLE
YouTool store blip is broken

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#30]
**What is the bug, be thorough.**
Standing on the blip at the YouTool 3052 doesn't give you the option to open the store. 
I stood closer to the door and it showed the option for the store momentarily, then disappeared again.

**How can we reproduce this bug?**
Try and open the store at YouTool. I don't believe any special steps are required to reproduce this

**Images**
https://i.imgur.com/MKvweyY.png

**Other info**

**Comment by factorAD** [comment]
UPDATE:
Not completely broken. Just very temperamental. You have to face away, in a certain spot. Same traffic with the blip at the nearest gas station/store.
You have to be in this position for the store to show up
https://i.imgur.com/vUVYhDk.png

**Comment by Hurstzy** [comment]
You can open you tool, you just have to be in the center of the blip.
