### ISSUE TITLE
Gas Pumps

### ISSUE THREAD

**Issue by AdvanceGamerPlayz** [Hurstzy/ShorelineRoleplay#300]
**What is your suggestion?**
[Add the gas bumps back to LSIA so we can refuel our aircrafts]

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by Hurstzy** [comment]
Thank you for your suggestion/report. This will be resolved with the large scale update that will be dropping this month. The gas pumps were never intended to be removed.
