### ISSUE TITLE
Meet sales 

### ISSUE THREAD

**Issue by Viator38** [Hurstzy/ShorelineRoleplay#301]
i had 2 stacks of 30 deer meat and 1 stock of 26 i was able to sale one of the 30 but then i removed cause i couldn’t sale the 30 and 26 i had and then i come back and they disappear.. i did /ensureinv and nothing.. idk why this keeps happening

**Comment by DerekStealth** [comment]
damn, back to drug we go

**Comment by factorAD** [comment]
Anticipated to be fixed per https://discord.com/channels/586599199370510338/721543022789001257/802432317208789002
