### ISSUE TITLE
Bank robberies

### ISSUE THREAD

**Issue by RCBlitz69** [Hurstzy/ShorelineRoleplay#302]
**What is the bug, be thorough.**
Hacking into the bank glitches you and you cant even hack it starts the animation but nothing happens no hacking screen pops up or anything. You either gotta relog or get a staff member to freeze and unfreeze you. Could this get fixed so bank robberies can  be done again because there is no actual way of robbing it anymore with the hacking glitched

**How can we reproduce this bug?**

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by factorAD** [comment]
Change log 1/23/21
