### ISSUE TITLE
Jewelry Robbery

### ISSUE THREAD

**Issue by DerekStealth** [Hurstzy/ShorelineRoleplay#303]
**What is your suggestion?**
[A Jewlery Robbery Script}

Is your suggestion related to a current issue?
[Well if I have to be honest bank robberys are getting pretty old so I think Jewelry robberys could be different and funner ]

**Other info**
https://github.com/esx-community/esx_vangelico_robbery possible script

**Comment by Hurstzy** [comment]
Thank you for your suggestion/report. More robberies will be added with the large scale update that will be dropping this month.
