### ISSUE TITLE
Comma Issue

### ISSUE THREAD

**Issue by Astro868** [Hurstzy/ShorelineRoleplay#305]
**What is the bug, be thorough.**
[If you run then hit comma you will die instantly]

**How can we reproduce this bug?**
[run then press comma]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
Thank you for your suggestion/report. This will be resolved with the large scale update that will be dropping this month.
