### ISSUE TITLE
Bait Car 

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#307]
LETS BRING BAIT CAR BACK 

https://forum.cfx.re/t/release-baitcarpro/263512/82

**Comment by StokesyBoi** [comment]
I wish, I miss doing bait car operations. It was so good, might actually be able to have some decent rp on bank robberies if we got it again.

**Comment by Hurstzy** [comment]
This was a mechanic that was used for the complete opposite of what it was intended for. This will not make a return.
