### ISSUE TITLE
Major taxi issues

### ISSUE THREAD

**Issue by CasualAnarchyy** [Hurstzy/ShorelineRoleplay#308]
**What is the bug, be thorough.**
Every time you press F6 to send out an ad for taxi it charges the company 6,000. Also, the on-off duty circle does not work. It only says “you clocked off duty” and it doesn’t do anything. Lastly when you spawn your car in the garage, it spawns facing the wall, not the garage door. 

**How can we reproduce this this bug?**
Log on as taxi (I will hire you if needed) and try to spawn a car, send out an ad, or clock off.

**Images**
I will send pictures to anyone that needs them. 
**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
Thank you for your suggestion/report. This will be resolved with the large scale update that will be dropping this month.
