### ISSUE TITLE
Add /calladmin and ids back

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#309]
**What is your suggestion?**
Add /calladmin and ids back (ids where you don't have to press f10)

Is your suggestion related to a current issue?
Yes, if you get rdmed, you can't report because 1. you can't f10 2. you can't do /report without having their id

**Other info**

If there is a big group of people rdming a vdming and you can't get there id, you are basically fucked, you can't call admin, and if you ask for one in chat they go "do /report with there id" We can't get there ids and this is just an excuse for staff members to not do their job and be lazy. 
As of lately the amount of rdm, vdm, and frp has gone up simply because you can't report without id, and it is difficult to get there id, and staff members just being lazy. I believe this would help us out drastically.

**Comment by factorAD** [comment]
Thanks, we'll make some adjustments
