### ISSUE TITLE
Add Binoculars

### ISSUE THREAD

**Issue by G2Bwolf** [Hurstzy/ShorelineRoleplay#310]
**What is your suggestion?**

I suggest we add a Binoculars script. This is so Game wardens can zoom in and actually see from hilltops. Its extremely hard to see what's going on when you are at a vantage point

Is your suggestion related to a current issue?

No

**Other info**

Link to a script https://www.gta5-mods.com/scripts/binocularsv

**Comment by factorAD** [comment]
Closing as it's a duplicate suggestion (although definitely noted)
https://github.com/Hurstzy/ShorelineRoleplay/issues/289
