### ISSUE TITLE
Voice Chat Inside of Vehicles Bug Report

### ISSUE THREAD

**Issue by G2Bwolf** [Hurstzy/ShorelineRoleplay#311]
**What is the bug, be thorough.**
Basically when someone gets into your vehicle their voice chat gets extremely loud. And its the same for the passenger when the driver is in the vehicle

**How can we reproduce this bug?**
Fix it so its just the same as outdoor voice chat

**Images**
N/a

**Other info**
n/a

**Comment by Hurstzy** [comment]
Thank you for your suggestion this will be resolved in the large scale update that will release this month.
