### ISSUE TITLE
Marijuana system is broken

### ISSUE THREAD

**Issue by famousvillain** [Hurstzy/ShorelineRoleplay#312]
So i just spent $825 on water & fertilizer at u-tools to grow plants, it was barely enough to fully grow my one plant, but after selling 2 weeds you only get about $900. Also i tried to harvest my plant and i got male seeds back 4 times in a row, only once did i ever get a female seed...i dont mean to complain but could you guys make the drug experience as enjoyable as yall try to for the police and medical experience cuz the server seems kinda one sided.

**How can we reproduce this bug?**
I don't think that's something you would wanna reproduce lol some people don't know yet how to get involved with more profitable drugs so if they were to start learning about the plants like myself they would end up having a bad experience and more than likely get frustrated.

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
this is one of the few servers i enjoy and it has great potential if we can just perfect the drug profits and the bugs such as the dope seeds. Also a staff member told me that weed was one of the worst routes to go but thats the only drug path alot of users know about so far until we climb the ranks so thats why im reporting this issue.

**Comment by Hurstzy** [comment]
The next large scale update will include a drug overhaul. We know the server seems quite one sided as we have out a lot of time into the emergency services. We are working on improving the civilian experience. Thank you for your suggestion.
