### ISSUE TITLE
Shooting with no guns

### ISSUE THREAD

**Issue by FrankiePope** [Hurstzy/ShorelineRoleplay#340]
### **What is the bug, be thorough.**
I went to jail, they took all my guns. Once my time was up i got out and hopped into a car with no guns, then pressed right click and it pulled out a gun while i didn't have any in my inventory and allowed me to shoot it.

**How can we reproduce this bug?**
By making sure the gun removing system works properly even though the gun is removed i can still use it in a car.
**Images**
![image](https://user-images.githubusercontent.com/79727395/109362922-9a0d7c00-7894-11eb-9ad9-d2c4b0e4939e.png)

![image](https://user-images.githubusercontent.com/79727395/109362972-a09bf380-7894-11eb-9f2b-c261ad291479.png)

**Other info**
I cant pull guns out while walking or running only when in a car.

**Comment by factorAD** [comment]
Thank you for your bug report. This will be resolved with the large scale update releasing 3/06/21
