### ISSUE TITLE
Add Spikestrip to Toolbox

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#35]
**What is your suggestion?**
Add Spikestrip to Toolbox

Is your suggestion related to a current issue?
Yes - no spikestrips in current LEO Toolbox.

**Other info**
[any other info? *delete this line to answer*]

**Comment by SammyB8185** [comment]
@MisterSandman401 Is this taken care of?

**Comment by Hurstzy** [comment]
This has been a feature, can be found in object spawner.
