### ISSUE TITLE
LEO Vehicle Textures and Lights Broken

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#36]
**What is the bug, be thorough.**
Chrysler 300, Durango have broken dirt textures and mess with the vehicle's texture completely. I.e floating dirt, splotched lighting and effects, etc.

DPS Charger visor lights are backwards.

**How can we reproduce this bug?**
Spawn the above cars.

**Comment by SammyB8185** [comment]
The charger lights should be fixed with the next restart, if not let me know, please.

**Comment by SammyB8185** [comment]
Hurszty you will have to add a "Keep vehicle clean" option to the leo toolbox to fix the dirt issues. I checked textures on them and there is nothing I can find to be oversized or incorrect.
