### ISSUE TITLE
Add more carwashes and lower cost

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#37]
**Why do you purpose this balance?**
More carwashes would allow people to keep their vehicles clean. Right now the only one is south los santos.

**What is your solution?**
Add more carwash locations.

**Other info**
[any other info? *remove line to answer*]

**Comment by SammyB8185** [comment]
Amen, please at least lower the price to about $10

**Comment by Hurstzy** [comment]
There are four carwashes currently. Three in LS and one in paleto. We will add more in the near future.
