### ISSUE TITLE
Trunk/Glovebox not working in owned vehicles.

### ISSUE THREAD

**Issue by Zenjitso** [Hurstzy/ShorelineRoleplay#373]
**What is the bug, be thorough.**
Cannot access trunk or glovebox inside player-owned vehicles. It displays the message "Second inventory is not available". I can get into a local car however and it works fine.

**Other info**
Video: https://www.youtube.com/watch?v=TjIhVwrJR7Q

**Comment by Hurstzy** [comment]
To be honest the inventory we have is pretty well to be blunt shit, a new one is in the works.

**Comment by gnich62** [comment]
If your car is on you shouldn't have any issues with getting the player-owned inventory. For some reason if the car is off it's not working.
