### ISSUE TITLE
Cop Garage Showcase

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#39]
**What is the bug, be thorough.**
Showcasing each car within the police garage is incredibly slow and buggy. As you scroll through to your desired car it hesitates to load all the cars you scrolled past.

**How can we reproduce this bug?**
Scroll through the police garage. 

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
This is not a "bug" we can fix, this is the client. They have to download all the vehicles on the list to see them.
