### ISSUE TITLE
Blimps falling out of the air

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#4]
**What is the bug, be thorough.**
Blimps randomly fall out of the air 

**How can we reproduce this bug?**
Not sure

**Images**
https://i.imgur.com/nAykDLF.png

**Other info**
Unable to drive through the blimps, although they only appear "in my eyes"

**Comment by Hurstzy** [comment]
This is a onesync issue (fivem's side) hence you only are seeing it on your end and others see it on there end in different places. Hopefully they can fix it eventually. Thanks for the report though.
