### ISSUE TITLE
DPS Suburban Lights

### ISSUE THREAD

**Issue by MisterSandman401** [Hurstzy/ShorelineRoleplay#41]
**What is the bug, be thorough.**
DPS Suburban lights are floating and all out of whack

**How can we reproduce this bug?**
Drive the Suburban.
**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
This should be fixed with the next restart, if not please let me know.
