### ISSUE TITLE
"NULL" Vehicles

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#43]
**What is the bug, be thorough.**
Harley Davidson in PDM shows as NULL in Garage.
Mustang in the Import Hanger for Supporters shows as NULL in Garage.
GMC Sierra Denali in the Import Hanger for Supporters shows as NULL in Garage

**How can we reproduce this bug?**
N/A

**Images**
![Screenshot (333)](https://user-images.githubusercontent.com/72477548/95273327-cacf1500-0810-11eb-8ce9-ea137f92e855.png)

**Other info**
N/A

**Comment by SammyB8185** [comment]
I will fix this Sunday when I get home.

**Comment by SammyB8185** [comment]
These should all be fixed with the next restart.
