### ISSUE TITLE
All amr cars say “null or bill”

### ISSUE THREAD

**Issue by jacobm9** [Hurstzy/ShorelineRoleplay#45]
**What is the bug, be thorough.**
All amr cars say null or nill

**How can we reproduce this bug?**
[answer here *remove this line to answer*]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
These should all be fixed with the next server restart, please let me know if they are not.
