### ISSUE TITLE
Skyline shows Null in garage

### ISSUE THREAD

**Issue by javin12** [Hurstzy/ShorelineRoleplay#49]
**What is the bug, be thorough.*
Skyline shows Null in garage

**How can we reproduce this bug?**
[answer here *remove this line to answer*]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
I will fix this Sunday when I get home.

**Comment by SammyB8185** [comment]
These should all be fixed with the next restart.
