### ISSUE TITLE
Bike Rental at Bus Station does not work

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#5]
**What is the bug, be thorough.**
The blip to "Rent a Bike" at the bus station near MRPD does not work. Pressing enter on a bike in the listing does nothing except close the menu

**How can we reproduce this bug?**
Stand on the blip, press E, press enter

**Images**
------

**Other info**
------

**Comment by Hurstzy** [comment]
Removed. Since we have spawn last location bike rentals are almost useless.
