### ISSUE TITLE
Fishing Prices and Sales. Rods breaking. Boat Fuel.

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#50]
**Why do you purpose this balance?**
Fishing Bait costs $1,000 for 10. You are unable to change the amount you purchase and have to pay the $1,000. 100 Fish sell for Roughly $400. Rods break pretty frequently and you must visit a store for more. When I rented a boat earlier for $3,500 i only recieved 28 Fuel, which does not give you enough to get far enough out to fish and return without swimming.

**What is your solution?**
Add the option for Single bait purchases or lower the cost of fishing bait by 20%-50%. Make the rod depletion lower or remove the breaking feature or Make a unbreakable fishing rod for a higher cost. When renting a boat make it spawn with 100% fuel or add a refueling station near boat rental areas.

**Comment by Hurstzy** [comment]
Patch for this next restart.
