### ISSUE TITLE
Harley Davidson Headlight

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#51]
**What is the bug, be thorough.**
The Harley Davidson for sale in PDM DOES NOT have a functioning headlight.

**How can we reproduce this bug?**
Add a similar headlight that other motorcycles have or that the new Suzuki has.

**Images**
![Screenshot (337)](https://user-images.githubusercontent.com/72477548/95377769-04eff380-08b1-11eb-9e3c-4f0416b87380.png)

**Other info**
The Suzuki Hyabusa has a awesome headlight and it would be great on the Harley.

**Comment by SammyB8185** [comment]
I will fix this Sunday when I get home.
