### ISSUE TITLE
Random Unoccupied AI Cars

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#52]
**What is the bug, be thorough.**
While driving around, unoccupied AI cars spawn and must be avoided to avoid damaging your own vehicle

**How can we reproduce this bug?**
Remove them somehow.

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
One-sync issue, server owners are in contact with fivem about this issue.
