### ISSUE TITLE
Re-Add the /repair option to Los Santos Custom's around the map.

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#53]
**What is your suggestion?**
Re-Add the /repair option to Los Santos Custom's around the map.

Is your suggestion related to a current issue?
Since there aren't alot of Mechanics available people can go to ANY LS Customs around the map and receive a full or partial vehicle repair. Its a HUGE issue when you have to run to get another vehicle or repair kit. Also, make it a rule that when a mechanic is on that people must make mechanic calls or go to the Shoreline Motors in the city.

**Other info**
The prior removal of this was basically the way I am suggesting we revert it to. When doing /repair and not at a LS Custom you would receive a 25% repair which most of the time would get you to the nearest Customs shop or garage.

**Comment by Hurstzy** [comment]
/repair was never intended to be in the public release. please use repair kits. you are damaging your vehicle you need to spend the money to fix it. if that means more responsible driving then do it!
