### ISSUE TITLE
Add "No Helmet"

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#55]
**What is your suggestion?**
Adding a "No Helmet" option or "Toggle Helmet" option for motorcyclists. Or make it to where we can decide what helmet we where when we ride.

Is your suggestion related to a current issue?
Any time you get on a motorcycle you automatically equipped a dirtbike helmet and it basically throws away any "look" for your character.

**Comment by Hurstzy** [comment]
Added.
