### ISSUE TITLE
Top Speed Adjustment on Suzuki Hayabusa GSX1300 2015. PLEASE

### ISSUE THREAD

**Issue by wig-daddy** [Hurstzy/ShorelineRoleplay#56]
**Why do you purpose this balance?**
The bike is very slow in-game (117 mph) compared to the actually IRL speed (roughly 200+MPH). Please feel free to test this yourself in-game.

**What is your solution?**
Make the Bike Mechanics/Top speed similar to the Kawasaki H2 in-game. The Hayabusa in-game only goes 117 MPH. The realistic speed of this vehicle is around 200 Mph, its a super-bike, please consider making its top speed and acceleration faster. 

**Other info**
Stock 2015 Hayabusa Info: Details
Year: 2015
Make: Suzuki
Engine: 4-stroke, Liquid-cooled, 4-cylinder, DOHC
Transmission: 6-speed
Energy: Suzuki Fuel Injection
Displacement: 1340 cc
Top Speed: 186 mph (Est.)

**Comment by SammyB8185** [comment]
I will fix this Sunday when I get home.

**Comment by SammyB8185** [comment]
This should be fixed with the next restart.
