### ISSUE TITLE
LEO License Plate Text

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#57]
**What is your suggestion?**
Add an option on the vehicle edit blip to change license plate text so LEO can put their callsigns in.

Is your suggestion related to a current issue?
Tangentially - if vehicles can be fixed so the extras save when you put them in the garage this feature would be great to have back

**Other info**

**Comment by Hurstzy** [comment]
Vehicle extras saving will be worked on, the leo license plate changing will not. We cannot do this as it would cause database issues as all license plates are unique.
