### ISSUE TITLE
Traffic advisory working light bars

### ISSUE THREAD

**Issue by ThePublicServant** [Hurstzy/ShorelineRoleplay#62]
Would be nice to have working traffic advisory bars for traffic stops roadwork control or if were broken down 

https://forum.cfx.re/t/non-els-lore-friendly-chp-vehicle-pack-working-spotlight-reflective-liveries-working-ta-bar/1103462

**Comment by Hurstzy** [comment]
That is an entire vehicle pack meaning we would have to redo the vehicle fleet which no one is up for right now.
