### ISSUE TITLE
PD Menus

### ISSUE THREAD

**Issue by peyder** [Hurstzy/ShorelineRoleplay#68]
**What is the bug, be thorough.**
A bug i have found, If you are in side a menu at the PD and open up a another menu by mistake it breaks the menu for you and you have to relog.
**How can we reproduce this bug?**
Go to a PD and open and different menu while in another one 

**Images**
N/A

**Other info**
[any other info? *remove this line to answer*]

**Comment by Hurstzy** [comment]
Can i have an example where this may occur? When did this happen to you? What menus opened?
