### ISSUE TITLE
Public Garage BUG

### ISSUE THREAD

**Issue by ShorelineLeo** [Hurstzy/ShorelineRoleplay#7]
**What is the bug, be thorough.**
When taking out a car from your garage, it breaks
**How can we reproduce this bug?**
Buy a car and put it in a public garage, take it out with its engine fine and it just breaks the engine

**Comment by Hurstzy** [comment]
I will be implementing a possible fix for this with the next restart.

**Comment by SammyB8185** [comment]
@ShorelineLeo is this fixed?
