### ISSUE TITLE
Honda Civic Type R Null

### ISSUE THREAD

**Issue by AdvanceGamerPlayz** [Hurstzy/ShorelineRoleplay#70]
**What is the bug, be thorough.**
[The Honda Civic Type R shows as NULL]

**How can we reproduce this bug?**
[Buy one and put it in your garage]

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
These should all be fixed with the next restart.
