### ISSUE TITLE
Organization Garage / Bunker Keys

### ISSUE THREAD

**Issue by RayzRayz** [Hurstzy/ShorelineRoleplay#76]
**What is your suggestion?**
[It would be a great idea to have the capability for organizations to have the ability to use a Community or Bunker like style garage for the organization's vehicles and aircraft. It could use a key giving system that you can give to certain people that are trusted, and be able to use. Can be limited in size by garage size, capacity etc, etc. This suggestion could also feature some sort of use with the boss menu that organizations could utilize to help keep track and or give permissions to certain people.]

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by Hurstzy** [comment]
Coming soon.
