### ISSUE TITLE
"Action Impossible" notification when trying to repair my Honda Civic Type R. Also a "null" car.

### ISSUE THREAD

**Issue by MikeDouglass** [Hurstzy/ShorelineRoleplay#78]
**What is the bug, be thorough.**
When I go to repair my vehicle I get a notification that says "Action Impossible"

**How can we reproduce this bug?**
As far as I know it only happens to me

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
Try purchasing another repair kit. Sometimes they will glitch out and visually stay there after they have been used, but they can not be used again.
