### ISSUE TITLE
Add back /repair w/ limited functionality

### ISSUE THREAD

**Issue by factorAD** [Hurstzy/ShorelineRoleplay#8]
**What is your suggestion?**
Allow /repair to "apply bubblegum" anywhere
Allow /repair to fully fix vehicle at mechanic shops (Flywheel gas station etc)

Is your suggestion related to a current issue?

**Other info**
Mechanics aren't active enough (not their own fault), sometimes stuff breaks

**Comment by Hurstzy** [comment]
You can go to a shop and buy a repair kit to fix your vehicles now.
