### ISSUE TITLE
dsync

### ISSUE THREAD

**Issue by Muratore2** [Hurstzy/ShorelineRoleplay#85]
ive had moments where cars appear right infront of my face and my car looks totaled and other things.
[answer here *remove this line to answer*]

**How can we reproduce this bug?**
idk its dsync and its such a mess.

**Images**

**Other info**
[any other info? *remove this line to answer*]

**Comment by SammyB8185** [comment]
You solved your own issues. Its dsync. Nothing we can do to fix that.
