### ISSUE TITLE
Lincoln Continental 2 seater

### ISSUE THREAD

**Issue by RayzRayz** [Hurstzy/ShorelineRoleplay#86]
**What is the bug, be thorough.**
The Lincoln Continental Sedan in the PDM, is a 4 seater and only 2 people are able to sit in the car. 

**How can we reproduce this bug?**
Sit in the car

**Images**
[answer here if you have images *remove this line to answer*]

**Other info**
Could be that the car it replaced was a 2 seater, or just could be dumb.

**Comment by SammyB8185** [comment]
It's just dumb, lol. That is the way the car modeler made it for some reason, so there is nothing that we can do about it unfortunately.
