### ISSUE TITLE
Toyota Donator Truck Tier 2

### ISSUE THREAD

**Issue by RayzRayz** [Hurstzy/ShorelineRoleplay#9]
**What is the bug, be thorough.**
The Toyota Tacoma pickup truck, in the tier 2 donator spot, one of the headlights is facing the rear of the truck, illuminating underneath the vehicle instead of in front of it

**How can we reproduce this bug?**
Just drive the Tacoma.

**Images**
No images are needed pretty self-explanatory.

**Other info**
Other than that the only other thing is the locking whenever you are accelerating with a controller.

**Comment by SammyB8185** [comment]
I have looked into this and unfortunately, it is an issue from the way it was modeled. There is nothing we can do to fix this.
