### ISSUE TITLE
Conflicting keybinds on controller

### ISSUE THREAD

**Issue by PF1anagan** [Hurstzy/ShorelineRoleplay#91]
**What is the bug? Be thorough.**
There are a number of keybinds on controller that conflict. Including:

**B** to blip LEO sirens/navigate menus **Issue:** Opens the car menu
**D-pad left** to turn LEO lights on. **Issue:** Opens inventory
**A** to sprint. **Issue:** Opens phone
**Right Trigger** to brake in vehicles. **Issue:** Locks vehicles
**Y** to get in and out of vehicles. **Issue:** Toggles chat

I feel I may have missed one or two but those are the main ones

**How can we reproduce this bug?**
Try any of the aforementioned actions via controller.

**Other info**
It would be great if this could be fixed as a priority as it is a major annoyance for controller players. Thanks

**Comment by RayzRayz** [comment]
Also, the right trigger locks and unlocks the vehicle. when accelerating, not braking

**Comment by tderboven21** [comment]
^^^^^^^^^ Please get this fixed asap. It would make the game 10X more enjoyable.

**Comment by tderboven21** [comment]
Still waiting on this...

**Comment by factorAD** [comment]
Controller keybinds fixed
