### ISSUE TITLE
Hunting activity

### ISSUE THREAD

**Issue by Astro868** [Hurstzy/ShorelineRoleplay#96]
**What is your suggestion?**
[Add someway of a hunting activity other then just rping hunting,[for example] [after killing a deer you can sell its meat the rarer the animal the more money] their should also be a station near the blimp to start hunting where you can buy quads side by sides etc

Is your suggestion related to a current issue?
[if yes then elaborate if no leave blank *delete line to answer*]

**Other info**
[any other info? *delete this line to answer*]

**Comment by factorAD** [comment]
Added
