### ISSUE TITLE
Revert to Half and Half

### ISSUE THREAD

**Issue by SheriffBoy** [Hurstzy/ShorelineRoleplay#98]
**What is your suggestion?**
Move this server back to half and half and not Full ESX. 

Is your suggestion related to a current issue?
YES! The Numbers of players are down to the GROUND all because of this update. So yes, very current and emergent issue. 
**Other info**
Ever since this update, player numbers have gone down. Speaking with some people, not everyone likes this update. When you go from having 25-40 people on the server a day to 7 people on a weekend night, there is clearly an issue and it needs to be fixed. I think we should go back to Half and Half and I am sure... a bunch of people would agree. Player satisfaction should be #1 and the players do not want full esx (as numbers show) so go back to half and half.

**Comment by Hurstzy** [comment]
It is not all about numbers to us. We want to do what we love to do. We enjoyed our time with vMenu but development got boring and we got burnt out. So we flipped pages. We are back in action with active development and more. Players that enjoy ESX will come i promise. Reverting wouldnt do much either. We already lost the players that were here for vMenu. Thank you for your concern though.
